name: Version and tag

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: >-
      ${{ fromJSON(format('{{"cloudconformity": "ubuntu-latest", "cloud-one-conformity": "ebf-pod-ubuntu-2004-slim@{0}-commitlint"}}', github.run_id))[github.repository_owner] }}
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # refers to actions/checkout@v3.1.0
      - uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516 # refers to actions/setup-node@v3.5.1
        with:
          node-version: 16
      - run: npm i npm@8 -g
      - name: Version and tag
        id: version
        uses: cloudconformity/npm-version-action@v0.3.0 # no need to a specific hash because we trust internal repos.
      - name: Get the output version
        run: echo "The version was ${{ steps.version.outputs.version }}"
