name: Version, Tag & Publish

on:
  push:
    branches: [main]

jobs:
  Version:
    runs-on: >-
      ${{ fromJSON(format('{{"cloudconformity": "ubuntu-latest", "v1-cspm-conformity": "ebf-pod-ubuntu-2004-slim@{0}-commitlint"}}', github.run_id))[github.repository_owner] }}
    outputs:
      tag_version: ${{ steps.version.outputs.version }}
    steps:
      - uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # v3.4.0
      - uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3.6.0
        with:
          node-version: 16
      - run: npm i npm@8 -g
      - name: Version and tag
        id: version
        uses: cloudconformity/npm-version-action@v0.3.0 # no need to a specific hash because we trust internal repos.
      - name: Get the output version
        run: echo "The version was ${{ steps.version.outputs.version }}"

  Publish:
    needs: Version
    runs-on: >-
      ${{ fromJSON(format('{{"cloudconformity": "ubuntu-latest", "v1-cspm-conformity": "ebf-pod-ubuntu-2004-slim@{0}-commitlint"}}', github.run_id))[github.repository_owner] }}
    env:
      ARTIFACTORY_TOKEN: ${{ secrets.ARTIFACTORY_TOKEN }}
      ARTIFACTORY_TOKEN_EMAIL: ${{ secrets.ARTIFACTORY_TOKEN_EMAIL }}
      ARTIFACTORY_URL: ${{ secrets.ARTIFACTORY_URL_VIRTUAL }}
      ARTIFACTORY_URL_PUBLISH: ${{ secrets.ARTIFACTORY_URL }}
    steps:
      - uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # v3.4.0
        with:
          persist-credentials: false
          ref: ${{needs.Version.outputs.tag_version}}
      - uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3.6.0
        with:
          node-version: 16
      - run: npm i npm@8 -g
      # Install
      - run: npm config set registry https://$ARTIFACTORY_URL
      - run: npm config set replace-registry-host npm.pkg.github.com
      - run: npm config set //$ARTIFACTORY_URL:_auth "$(echo -n $ARTIFACTORY_TOKEN_EMAIL:$ARTIFACTORY_TOKEN | base64 -w 0)"
      - run: npm config set //$ARTIFACTORY_URL:email "$ARTIFACTORY_TOKEN_EMAIL"
      - run: npm config set //$ARTIFACTORY_URL:always-auth true
      - run: npm ci
      - run: npm run build --if-present
      # Publish to Artifactory
      - run: npm config set registry https://$ARTIFACTORY_URL_PUBLISH
      - run: npm config set //$ARTIFACTORY_URL_PUBLISH:_auth "$(echo -n $ARTIFACTORY_TOKEN_EMAIL:$ARTIFACTORY_TOKEN | base64 -w 0)"
      - run: npm config set //$ARTIFACTORY_URL_PUBLISH:email "$ARTIFACTORY_TOKEN_EMAIL"
      - run: npm config set //$ARTIFACTORY_URL_PUBLISH:always-auth true
      - run: npm publish
